<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\import%28dark%29.png" />
    <None Remove="assets\ImportIcon.png" />
    <None Remove="assets\settings%28dark%29.png" />
    <None Remove="assets\settings.png" />
    <None Remove="assets\shuffle.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.119" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\import(dark).png" />
    <Resource Include="assets\ImportIcon.png" />
    <Resource Include="assets\settings(dark).png" />
    <Resource Include="assets\settings.png" />
    <Resource Include="assets\shuffle.png" />
  </ItemGroup>

</Project>
