; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5E2289F1-E99C-422C-908C-3F4A5BC76A8B}
AppName=Flash Cards
AppVersion=1.0
;AppVerName=Flash Cards 1.0
AppPublisher=ChrisMorr154
AppPublisherURL=https://github.com/ChrisMorr154/FlashCard-App
AppSupportURL=https://github.com/ChrisMorr154/FlashCard-App
AppUpdatesURL=https://github.com/ChrisMorr154/FlashCard-App
DefaultDirName={autopf}\Flash Cards
DefaultGroupName=Flash Cards
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir=C:\Users\Christian\Desktop\Installer
OutputBaseFilename=FlashCardAppSetup
SetupIconFile=brain.ico
SolidCompression=yes
WizardStyle=modern stellar

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "..\Publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: "..\Installer\brain.ico"; DestDir: "{app}"

[Icons]
Name: "{group}\{cm:UninstallProgram,Flash Cards}"; Filename: "{uninstallexe}" 
Name: "{group}\Flash Cards"; Filename: "{app}\FlashCardApp.exe"; IconFilename: "{app}\brain.ico"
Name: "{commondesktop}\Flash Cards"; Filename: "{app}\FlashCardApp.exe"
Name: "{commondesktop}\Flash Cards"; Filename: "{app}\FlashCardApp.exe"; IconFilename: "{app}\brain.ico"


